const mongoose = require("mongoose");
const fs = require("fs");
const path = require("path");
// Ensure it loads .env properly
const dotenv = require("dotenv");
dotenv.config({ path: path.join(__dirname, "../.env") });

const fakeProfileService = require("../modules/Admin/fakeProfiles/fakeProfile.service");
const utils = require("../modules/auth/auth.utils");
const User = require("../modules/auth/auth.model");
const Profile = require("../modules/profile/profile.model");
const {
    connectWithRetry,
    registerGracefulShutdown,
} = require("../config/database");
async function seedFeedTestingProfiles() {
    try {
        console.log("🚀 Connecting to MongoDB...");
        await connectWithRetry(process.env.MONGODB_URI);
        registerGracefulShutdown();
        // await mongoose.connect(process.env.MONGODB_URI);
        console.log("✅ Connected.");

        // Clean up previously generated feed test profiles so db doesn't explode
        const batchId = "feed_perf_test";

        console.log("🧹 Cleaning up old test profiles generated by this script...");
        const oldUsers = await User.find({ "fakeProfileMeta.batchId": batchId }).select("_id").lean();
        if (oldUsers.length > 0) {
            const oldUserIds = oldUsers.map(u => u._id);
            await User.deleteMany({ _id: { $in: oldUserIds } });
            await Profile.deleteMany({ userId: { $in: oldUserIds } });
            console.log(`✅ Deleted ${oldUserIds.length} old test profiles.`);
        }

        console.log("⏳ Generating 1,000 High-Quality Fake Profiles...");
        console.log("   (This will use your existing fake profile service, safely)");

        let allCreatedUsers = [];

        // Run in 2 batches of 500
        for (let i = 0; i < 2; i++) {
            const result = await fakeProfileService.bulkCreateFakeProfiles({
                count: 500,
                gender: i % 2 === 0 ? "women" : "men", // Mix of genders
                city: "Sydney",
                adminId: new mongoose.Types.ObjectId()
            });

            const userIds = result.profiles.map(p => p.user._id);

            // Tag them explicitly for easy cleanup later
            await User.updateMany(
                { _id: { $in: userIds } },
                { $set: { "fakeProfileMeta.batchId": batchId } }
            );

            allCreatedUsers.push(...result.profiles.map(p => p.user));
            console.log(`✅ Batch ${i + 1}/2 created!`);
        }

        console.log("🔑 Extracting Access Tokens for 100 Virtual Users...");
        const virtualUsers = allCreatedUsers.slice(0, 100);
        const tokens = virtualUsers.map(user => utils.generateAccessToken(user));

        const dataDir = path.join(__dirname, "../k6/data");
        if (!fs.existsSync(dataDir)) {
            fs.mkdirSync(dataDir, { recursive: true });
        }

        const tokensFilePath = path.join(dataDir, "feed_tokens.json");
        fs.writeFileSync(tokensFilePath, JSON.stringify(tokens, null, 2));

        console.log(`✅ Saved ${tokens.length} tokens to k6/data/feed_tokens.json for load testing.`);
        console.log("🎉 Seeding complete. You can now run the load test!");
        process.exit(0);

    } catch (err) {
        console.error("❌ Seeding failed:", err);
        process.exit(1);
    }
}

seedFeedTestingProfiles();
