name: Node.js CI

on:
  push:
    branches: ["main", "dev", "staging"]
  pull_request:
    branches: ["main", "dev", "staging"]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524742306563bd83011 # v4.0.2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint

      - name: Run Security Audit
        run: npm audit --audit-level=high

      - name: Run Tests
        run: npm test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f921623015db40065ad47a25a1913317835166aa # v3.1.0

      - name: Build Docker Image (Dry Run)
        uses: docker/build-push-action@2cd201d51f2f65a7f92025ed9969634e8ec6aa4b # v5.1.0
        with:
          context: .
          push: false
          tags: mafs-backend:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Build
        run: npm run build