name: Node.js CI

on:
  push:
    branches: ["main", "dev", "staging"]
  pull_request:
    branches: ["main", "dev", "staging"]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image (Dry Run)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: mafs-backend:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Build
        run: npm run build