const NOTIFICATION_TYPES = {
  NEW_MATCH: 'NEW_MATCH',
  NEW_MESSAGE: 'NEW_MESSAGE',
  NEW_LIKE: 'NEW_LIKE',
  NEW_SUPER_LIKE: 'NEW_SUPER_LIKE',
  GIVEAWAY_WINNER: 'GIVEAWAY_WINNER',
  PRIZE_DELIVERED: 'PRIZE_DELIVERED',
  ADMIN_NOTIFICATION: 'ADMIN_NOTIFICATION',
  PREMIUM_EXPIRY: 'PREMIUM_EXPIRY',
  ADMIN_BROADCAST: 'ADMIN_BROADCAST',
  KYC_VERIFIED: 'KYC_VERIFIED',
  KYC_REJECTED: 'KYC_REJECTED'
};
module.exports = {
  NOTIFICATION_TYPES
};