const NOTIFICATION_TYPES = {
  NEW_MATCH: 'NEW_MATCH',
  NEW_MESSAGE: 'NEW_MESSAGE',
  NEW_LIKE: 'NEW_LIKE',
  GIVEAWAY_WINNER: 'GIVEAWAY_WINNER',
  PRIZE_DELIVERED: 'PRIZE_DELIVERED',
  ADMIN_NOTIFICATION: 'ADMIN_NOTIFICATION'
};

module.exports = {
  NOTIFICATION_TYPES
};